config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jobs
  root "jobs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
before_action :find_job , except: [:create , :index , :new]  

  def index
  	if params[:category].blank?
  	@jobs = Job.all
    else
    	
    @category = Category.find_by(name: params[:category])
    @jobs = @category.jobs
    end	
  end
  def show
  end	
  def new
  	@job = Job.new
  
  end	
  def create
  	@job = Job.new(jobs_params)
  	if @job.save
  		
  		redirect_to @job 
  	else
  	   
  	    redirect_to :back	
    end
  end
  
     
  def destroy
  	@job.destroy
  	redirect_to root_path
  end
  
  def update
    if @job.update(jobs_params)
      redirect_to @job
    else 
     render 'edit'     
    end
  end
  def show
  
  end

  def edit

  end

  private
  
  def jobs_params
    params.require(:job).permit(:title , :description , :company , :url ,:category_id)
  end	
  def find_job
  	@job = Job.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job , html:{class: "form-vertical"}) do |f| %>
  <%= f.input :title %>
  <%= f.collection_select :category_id , Category.all, :id , :name ,{prompt: "select 1 category"} %>
  <%= f.input :description %>
  <%= f.input :url %>
  <%= f.input :company %>
  <%= f.button :submit %>
<% end %>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
  <%= render 'form' %>

app/views/jobs/index.html.erb
<div id="jobs">
  <% @jobs.each do |job| %>
    <div class="job">
      <h2>
        <%= link_to job.title, job %>
      </h2>
      <p>
        <%= job.company %>
      </p>
    </div>
  <% end %>
</div>


<!--
<h1>Jobs#index</h1>
<% @jobs.each do |job|%>

<p><h2><%=link_to job.title , job %></h2>
<h5><%=job.description %></h5>
	<h5>	<%=job.url %></h5>
<h5>	<%=job.company %></h5></p>
<h5>	<%=job.category.name %></h5></p>
<% end %>
<%=link_to "back" , jobs_path %>
<%=link_to "New Job" , new_job_path %>
-->

app/views/jobs/new.html.erb
<h2>New JOB</h2>
<%=render 'form'%>
<%=link_to "back", root_path %>

app/views/jobs/show.html.erb
<div id="jobs">
  <div class="job">
    <h2>
      <%= @job.title %>
    </h2>
    <p>
      <%= @job.description %>
    </p>
    <p>
      <%= @job.company %>
    </p>
    <button class="btn btn-default">
      <%= link_to "Apply for Job", @job.url %>
    </button>
  </div>
</div>
<div id="links">
  <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
  <%= link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default" %>
  <%= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class= 'navbar navbar-default'>
      <div class='content'>  
         <div class='navbar-brand ' >Rails Jobs</div>
    <ul class="nav navbar-nav">
     <li>
          <%= link_to "All Jobs", root_path %>
        </li>
        <% Category.all.each do |category| %>
          <li>
            <%= link_to category.name, jobs_path(category: category.name) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link" %>
    </div>
  </nav>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <%= yield %>
    </div>
  </div>
</body>
</html>
<!--
    <% Category.all.each do |category| %>
    <%= link_to category.name , jobs_path(category: category.name) %>
    
    <% end %>

    <%= yield %>
  </body>
</html>  -->
<!--, @jobs_path(category: category.name)
  %nav.navbar.navbar-default
    .container
      .navbar-brand Rails Jobs
      %ul.nav.navbar-nav
        %li= link_to "All Jobs", root_path
        - Category.all.each do |category|
          %li= link_to category.name, jobs_path(category: category.name)
      = link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"
  .container
    .col-md-6.col-md-offset-3
      = yield-->